### ISSUE TITLE
not finding data when on R shiny

### ISSUE THREAD

**Issue by jst04004** [rsquaredacademy/olsrr#164]
Trying to run ols_step_both_p(model). It works in a local, manual environment, but when using within an app in R shiny, I get the error "rror in eval(model$call$data) : object 'datatibble' not found".
 in debug mode when running the app locally, I can see my variable datatibble in the memory environment. The "model" variable populates as well, so the first line of code below is working. 

relevant code is as follows:
 model<-lm(response~l1+l2+l3+l4+l5+l6+l7, data = datatibble)
        bestmodel<-ols_step_both_p(model)

**Comment by aravindhebbali** [comment]
When used with Shiny, the step-wise selection methods can't find the data since olsrr uses `eval()` to extract the underlying data. This is a flaw in the package and will be fixed in the next release. A temporary solution is to explicitly specify the data set which is what we have done in the [xplorerr](https://github.com/rsquaredacademy/xplorerr/) package. 

You can see the workaround in [this](https://github.com/rsquaredacademy/xplorerr/blob/master/inst/app-olsrr/logic/logic_mselection2.R#L751) file. Let us know if it helps and if you have any further questions.

**Comment by jst04004** [comment]
Great! thanks so much. I found a not quite as elegant solution just forcing my variable to be global. Thank you for the package, its good stuff.
